### ISSUE TITLE
Check integrity of yaml-configuration file

### ISSUE THREAD

**Issue by kleinski** [elabit/robotmk#153]
It would be nice to know, if the yaml configuration file has been changed manually on the robot running host.
Maybe it is possible to optionally generate a md5 hash at the site during the baking process, store that at the site to compare it with the hash which shall be generated periodically at the robot running host, being transferred included in the plugin output.

**Comment by simonmeggle** [comment]
Great idea, thanks. 
Storing the hash during the agent baking could be difficult (more exactly: accessing it then during the check). Also housekeeping can be difficult.  
But the hash could be also delivered within a file to the agent. The agent plugin could locally compare the hashed `robotmk.yml` with the stored hash and raise an alarm on the "Robotmk" service about diverging configuration.

**Comment by simonmeggle** [comment]
I will close this ticket... 
The demand for this feature is justified, but if we implement it, we would also have to check whether the checksums of plugins are still the same. 
Admins should always be aware when they customize files that an automatic process is actually responsible for distributing. 
But thanks for the suggestion!
