### ISSUE TITLE
Global configuring of retries and --exitonfailure

### ISSUE THREAD

**Issue by kleinski** [elabit/robotmk#179]
It would be a comfortable option to set the "Handling of failed tests/Suites" and "Exit on failure" globally instead of suite specific.

**Comment by simonmeggle** [comment]
I'll take this into account, thanks. 

For all the others: currently you can specify suites and their parameters in the bakery - or just leave the suites empty. In this case, Robotmk will execute all RF suites it can find in `robotdir`. 
This "catch all mode" is handy but currently allows _absolutely no_ configuration. 

This issue suggests to allow certain parameters to be defined globally, however - even if no suites are specified.
