### ISSUE TITLE
Define individual configuration dir for robotmk.yml

### ISSUE THREAD

**Issue by kleinski** [elabit/robotmk#199]
In a scenario where the bakery is not used to deploy the agent, but the suites are deployed via e.g. gitlab, it would be useful to define a variable (formerly known as agent_config_dir) in which directory the robotmk.yml is stored, which will be used by the robotmk-runner. So that possible configuration changes may be deployed via the same mechanism.

Or at least it would be good to have a switch in the setup to decide, if the robotmk.yml will be stored in the agent config or in the defined robot directory.

**Comment by kleinski** [comment]
Or at least it would be good to have a switch in the setup to decide, if the robotmk.yml will be stored in the agent config or in the defined robot directory.

**Comment by simonmeggle** [comment]
Question: could `robotmk.yml` not also be created/edited automatically at the location where it is saved by default? 
What would be the advantage to make the location configurable?

**Comment by kleinski** [comment]
In case you have separate deployments of the checkmk agent (bakery) and the robot suites (e.g. gitlab) and you don't want to mix up the deployment of robotmk.yaml with other configuration files in ..\checkmk\agent\config but want to configure it separately. 

I do have a scenario where the agent won't be deployed, but there may be changes in the robotmk.yaml when single suites shall be deactivated temporarily. So I let the file deploy to the robot folder and have a local check running which compares the config files in robot and in config. If they are not identical, the file from the robot folder will be copied to the config folder. But I do not want to have the config folder be part of a repository.

**Comment by simonmeggle** [comment]
Ok, I see. 

The only place where I can give robotmk parametrs is the `robotmk.yml`.
 
I could put the path to an externalYML file in the global section of the agent YML file.
 
There is a fixed order, which values can override others: 

- 1. defaults, which are stored in `robotmk.py`
- 2. values in the `robotmk.yml` (agent, deployed by bakery) 
- 3. environment variables (e.g. `ROBOTMK_global_log_level=DEBUG`)

Between step 2 and 3 I see your requirement. 

Robotmk could try to read the specified external YML file, possibly overwriting values that are either default or in the agent YML. 
But with environment variables everything would still be overwriteable. 

The advantage is that Robotmk always has a valid YML as a base, which you can enrich with your own YML as you need.

What do you think about that?

**Comment by kleinski** [comment]
> I could put the path to an externalYML file in the global section of the agent YML file.

Yes, I thought about that too: Configure it like an apache server.

Would be really useful and the order of the overriding is totally senseful.

**Comment by simonmeggle** [comment]
Won't be done in RMKv1
