### ISSUE TITLE
Runner execution interval not respected

### ISSUE THREAD

**Issue by kkensy** [elabit/robotmk#214]
We have noticed some deviation from the configured runner execution interval:

> Result cache time: 	10 minutes
> Runner execution interval: 	5 minutes

Actual interval:

> $ grep -o -E ".*(Suites to start|Quitting Runner)" /var/log/robotmk/robotmk_runner.log | tail
> 2023-02-07 13:00:36,294  RMKrunner [2751706]    INFO:  => Suites to start
> 2023-02-07 13:02:04,096  RMKrunner [2751706]    INFO: ... Quitting Runner
> 2023-02-07 13:07:37,391  RMKrunner [2755997]    INFO:  => Suites to start
> 2023-02-07 13:09:04,702  RMKrunner [2755997]    INFO: ... Quitting Runner
> 2023-02-07 13:14:38,733  RMKrunner [2760253]    INFO:  => Suites to start
> 2023-02-07 13:16:05,315  RMKrunner [2760253]    INFO: ... Quitting Runner
> 2023-02-07 13:21:40,450  RMKrunner [2764371]    INFO:  => Suites to start
> 2023-02-07 13:23:06,434  RMKrunner [2764371]    INFO: ... Quitting Runner
> 2023-02-07 13:28:41,575  RMKrunner [2768855]    INFO:  => Suites to start
> 2023-02-07 13:30:06,751  RMKrunner [2768855]    INFO: ... Quitting Runner

robotmk server component version: 1.4.1

**Comment by simonmeggle** [comment]
Can you check if the plugin folder for Robotmk (async) is named "600"?

**Comment by kkensy** [comment]
Do you mean this one?
> $ find /usr/lib/check_mk_agent/plugins/ -name robotmk-runner.py
> /usr/lib/check_mk_agent/plugins/300/robotmk-runner.py

**Comment by simonmeggle** [comment]
Ah, sorry. For 5 minutes 300s are correct, not 600 as I mentioned. Thanks. 
Must be investigated, thanks for reporting this!

**Comment by simonmeggle** [comment]
Wont be done in RMK1 - executed by the scheduler in RMKv2.
