### ISSUE TITLE
Number of XML/HTML log files to keep on the host

### ISSUE THREAD

**Issue by kkensy** [elabit/robotmk#215]
In the event of a large-scale or lengthy service interruption, many log files can be generated, which require a lot of disk space due to possible screenshots.

Can the parameter _'Number of days to keep Robot XML/HTML log files on the host'_ of the _'Robotmk (Linux, Windows)'_ agent rule be extended with hour or count options?

**Comment by simonmeggle** [comment]
Thanks for the suggestion. You are right, age can be a proper way to measure the amount of logs, but can also complete wrong. Noted!

**Comment by simonmeggle** [comment]
Transferred to Jira
