### ISSUE TITLE
Robot framework service discovery level - node whitelist

### ISSUE THREAD

**Issue by kkensy** [elabit/robotmk#216]
How about allowing a whitelist for nodes in the _'Detection level of services from robot output'_ parameter of the _'Robot framework service detection'_ service discovery rule?

**Comment by simonmeggle** [comment]
Thanks for the suggestion! Do you really have a use case for a _whitelist_ here? 
I always thought that a blacklist is sufficient here...

**Comment by kkensy** [comment]
It's not really a good use case :sweat_smile: - we stumbled across this after we tweaked our robot. We moved the keywords into login, navigation, and teardown tasks - renaming them multiple times. We wanted only two of the tasks to show up as checkmk services without editing the blacklist after each tweak and ended up using a regex like `^[^V]` . Both monitored test cases start with a "V" and test the status of a system component.

**Comment by simonmeggle** [comment]
Ah, I see. 
I would strongly suggest to have ramp-up work as well as cleanup-tasks in `Test Setup` and `Test Teardown` keywords. 
In this way you can have as many tests as you want - Robot Framework will do the Setup and Teardown work for every test. 
Seems like overkill but has the bis advantage that you can start tests individually and make use of the "Failed test re-execution" of Robotmk.
